version: '3.8'

services:
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - bsn-network
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "1025"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    build:
      context: .
      dockerfile: Dockerfile
    image: bsn/bsn:1.0.0
    ports:
      - "8088:8088"
    secrets:
      - jdbc_url
      - jdbc_password
    environment:
      - JDBC_URL=${JDBC_URL}
      - JDBC_USERNAME=${JDBC_USERNAME}
      - PASSWORD=${PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER_NAME=${MAIL_USER_NAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - bsn-network
    restart: unless-stopped

networks:
  bsn-network:
    driver: bridge

volumes:
  postgres-data:
    name: postgres-data-volume