version: '3.8'

services:
  postgres:
    container_name: postgres-bsn
    image: postgres:latest
    environment:
      POSTGRES_DB: book-social-network
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d book-social-network"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    build:
      context: .
      dockerfile: Dockerfile
    image: bsn/bsn:1.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book-social-network
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8088:8088"
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres-data:
    name: postgres-data-volume