spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${MAIL_HOST}
    port: 1025
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 300
  mailing:
    frontend:
    activationUrl: http://localhost:5000/activate-account
  upload:
    photos-output-path: /uploads
server:
  port: 8088
