name: BSN Backend API CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - book-social-network/**
      - 'docker-compose.yml'
      - .github/workflows/pipeline-backend.yml
      - '**/Dockerfile'

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
        fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile project
        run: |
          ./mvnw clean compile
    

  unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
      fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
      java-version: '21'
      distribution: 'temurin'
    -name: Run unit tests
    run: |
      cd book-social-network
      ./mvnw clean test
      
  build:
    runs-on: ubuntu-latest
    name: Build backend
    needs: [compile, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backend image
        run: |
          cd book-social-network
          ./mvnw clean package -DskipTests

  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build the project
        run: |
          cd book-social-network
          ./mvnw clean package -DskipTests

      - name: Extract project version
        id: extract_version
        run: |
          cd book-social-network
          echo "VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
         

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: book-social-network
          file: book-social-network/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${ secrets.DOCKER_USERNAME }/bsn-api:${{ steps.extract_version.outputs.VERSION }}
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}


  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Create deployment folder
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "mkdir -p ci-cd"

      - name: Copy docker-compose file
        run: scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:ci-cd/docker-compose.yml

      - name: Set environment variables and deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
          export EMAIL_HOSTNAME=${{ secrets.EMAIL_HOST }}
          export EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          cd ci-cd
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF
