name: BSN Backend API CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - 'docker-compose.yml'
      - '.github/workflows/pipeline-backend.yml'
      - '**/Dockerfile'

jobs:
  build-and-push-image:
    name: Build & Push Docker Image to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests

      - name: Extract project version
        id: extract_version
        run: |
          echo "VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: book-social-network
          file: book-social-network/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/bsn-api:${{ steps.extract_version.outputs.VERSION }}

  deploy-to-azure:
    name: Deploy to Azure App Service
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/bsn-api:${{ needs.build-and-push-image.outputs.extract_version.outputs.VERSION }}
